#!/bin/sh

ipurl=icanhazip.com

case "$1" in
    -h|--help|help|)
    cat <<EOF
Usage: $0 [subcommand [arguments]]

Updates DNS entries via nsupdate using configured credentials in
/etc/ddns/ (the update directory).

	help		show this help message
	run		update each host setup in /etc/ddns/
	add HOSTNAME 	add HOSTNAME to /etc/ddns/
	delete HOSTNAME	remove HOSTNAME from /etc/ddns/
EOF
    ;;
    add)
	dnssec-keygen -a RSASHA512 -K /etc/ddns -T KEY -n HOST "$2"
	;;
    delete)
	rm /etc/ddns/k"$2".+*
	;;
    run)
	for key in /etc/ddns/K*.key; do
	    # now we get the host from the KEY RR
	    host="$(cut -d ' ' -f 1 "$1")"

	    # now we update the host
	    {
		added_address=false
		echo "ttl 300"

		# Check for IPv4 addresses that we can bind to and don't
		# go through NAT
		echo "delete $host A"
		if curl --interface "$(curl -s4 "$ipurl")" -s4 "$ipurl" > /dev/null; then
		    added_address=true
		    echo "add $host $ttl A $(curl -s4 "$ipurl")"
		fi

		# Check for IPv6 addresses that we can bind to and don't
		# go through NAT
		echo "delete $host AAAA"
		if curl --interface "$(curl -s6 "$ipurl")" -s6 "$ipurl" > /dev/null; then
		    added_address=true
		    echo "add $host $ttl AAAA $(curl -s6 "$ipurl")"
		fi

		# email provisioning
		echo "delete $host MX"
		echo "delete $host TXT \"v=spf1 mx -all\""
		if "$added_address" && systemctl is-active postfix > /dev/null; then
		    echo "add $host $ttl MX 10 $host"
		    echo "add $host $ttl TXT \"v=spf1 mx -all\""
		fi

		# ssh keys
		echo "delete $host SSHFP"
		if "$added_address" && ssh-keygen -r "" > /dev/null; then
		    ssh-keygen -r "$host" | sed "s/.*/add &/"
		fi

		# log the update
		if "$logupdates"; then
		    echo "show"
		fi

		echo "send"
	    } | nsupdate -k "$1"
	done
	;;
esac
